### ISSUE TITLE
Unable to download chapters of webtoon if chapter titles contain illegal characters

### ISSUE THREAD

**Issue by Niregato** [RustingRobot/Kea#2]
When downloading webtoon chapters with titles contain illegal characters (such as *), the following error message appears: 
https://user-images.githubusercontent.com/54008701/103303922-45768d80-4a18-11eb-986f-08f29c5079dc.png

**Comment by pzkt** [comment]
Good catch! The newest release now sanitizes the chapter names.
https://github.com/RustingRobot/Kea/releases/tag/v1.2.1
