### ISSUE TITLE
No .exe file in the zip donwload.

### ISSUE THREAD

**Issue by theproperexile** [RustingRobot/Kea#5]
I tried downloading the .zip and there is no .exe file in it, so the thing can't boot up properly.

**Comment by pzkt** [comment]
huh that's weird. To be sure, have you downloaded the .zip from here?: https://github.com/RustingRobot/Kea/releases/tag/v1.3.1

**Comment by theproperexile** [comment]
> huh that's weird. To be sure, have you downloaded the .zip from here?: https://github.com/RustingRobot/Kea/releases/tag/v1.3.1

yes i did

**Comment by pzkt** [comment]
Try this direct download link: [Kea.v1.3.1.zip](https://github.com/RustingRobot/Kea/files/6095294/Kea.v1.3.1.zip) The .exe should be included.
