### ISSUE TITLE
It probably is just my windows but kea doesnt work anymore

### ISSUE THREAD

**Issue by LittleBigTea** [RustingRobot/Kea#6]
**Describe the bug**
A description of what the bug is. When I hit start downloading it just says something about unhandled exception ( I tried youtube tutorials but they doesn't work)

**To Reproduce**
Steps to reproduce the bug. I tried downloading https://www.webtoons.com/en/horror/distant-sky/list?title_no=75

**Kea Version**
What version of Kea were you using? I'm using the latest one 1.3.1

**Comment by pzkt** [comment]
I have investigated this bug a little bit and I think I have found the problem. Webtoons has recently started to request an age verification on your first visit to their site. After you enter your birthday it saves it in your cookies and doesn't ask you again. (if you go to webtoons.com in incognito mode you can still see the age verification page).

If I append custom cookies to my download requests it should work again but I'm still in the testing phase.
Thank you for reporting this bug!

**Comment by pzkt** [comment]
Ok, I have released 1.3.2 which should hopefully fix the bug (https://github.com/RustingRobot/Kea/releases/tag/v1.3.2)
