### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by ghost** [RustingRobot/Kea#8]
**Describe the bug**
When I add something it doesn't go in the queue.

**To Reproduce**
Adding a comic to the software with queue, I was trying to read https://www.webtoons.com/en/action/omniscient-reader/episode-10/viewer?title_no=2154&episode_no=11 

**Kea Version**
What version of Kea were you using? Latest in releases.

**Comment by pzkt** [comment]
Kea actually requires the link of the page were all chapters are listed (for your example the link would be: https://www.webtoons.com/en/action/omniscient-reader/list?title_no=2154).
I hope this helps and sorry for the inconvenience.

**Comment by ghost** [comment]
> Kea actually requires the link of the page were all chapters are listed (for your example the link would be: https://www.webtoons.com/en/action/omniscient-reader/list?title_no=2154).
> I hope this helps and sorry for the inconvenience.

Thank's for the quick response, it fixed my issue. Thank you!
