### ISSUE TITLE
Suggestion.

### ISSUE THREAD

**Issue by ghost** [RustingRobot/Kea#9]
This isn't really a issue but I don't know where to put it. Is it possible to use the CBZ format? 

If you can do this, thank you!

**Comment by pzkt** [comment]
Yeah, feel free to post any suggestions you may have.
[Kea 1.3.4](https://github.com/RustingRobot/Kea/releases/tag/v1.3.4) can now save chapters as CBZ files

![image](https://user-images.githubusercontent.com/50629201/122651413-f1cc3d80-d138-11eb-8ba6-5a254ee9b364.png)
